version: '3.8'

services:
  backend:
    build: .
    links:
      - "db:database"
    ports:
      - 8080:8080

  db:
     image: postgres
     restart: always
     environment:
       POSTGRES_PASSWORD: passwd
     healthcheck:
      test: pg_isready -U postgres -d postgres 
      interval: 10s
      timeout: 3s
      retries: 3  
     ports:
       - 8001:5432

