version: '3.8'

services:
  db:
     image: postgres
     restart: always
     environment:
       POSTGRES_PASSWORD: passwd
     healthcheck:
      test: pg_isready -U postgres -d postgres 
      interval: 10s
      timeout: 3s
      retries: 3  
